Add last well known types
qitab/cl-protobufs pull request #247
Opened 2020-10-02 17:50 UTC by bkuehnert

This PR adds struct.proto, which is the last remaining well known types file from google/protobuf.

The commits in this PR are kind of messy, since part of the work was done when I was at Google, and part was after. I'm not totally sure if I can squash the commits for copyright reasons...

2020-10-02 18:13 UTC, bkuehnert commented
@qitab/googlers I fixed it.

2020-10-05 17:29 UTC, cgay requested changes

2020-10-05 17:29 UTC, cgay commented on json.lisp
> +            (value (pi::oneof-value oneof-data)))
This bit about finding the field descriptor just to find the type of the value is kind of nasty.  Maybe we can return two values from `oneof-value`: the value and the type.  That would remove the need to dig into low-level internals. But I see that's a defstruct slot so we'll need to make some changes. We can do this in a separate PR, but could you add a TODO comment?

2020-10-05 17:37 UTC, Slids commented on json.lisp
> +    ((google:struct)
Why?

2020-10-06 01:35 UTC, cgay commented on json.lisp
> +    ((google:struct)
Mainly because it seems odd that we treat Google's WKT as a special flower. You can ignore it.

2020-10-06 01:40 UTC, Slids commented on json.lisp
> +    ((google:struct)
Then we should remove the other special printer functions for user defined types.
It's feature creep for annoying reasons...

2020-10-06 17:44 UTC, cgay commented on json.lisp
> +    ((google:struct)
I'm not quite following you.

2020-10-13 04:14 UTC, bkuehnert commented on json.lisp
> +    ((google:struct)
While it would be nice (and probably easy) to make a general mechanism to handle special JSON printers, is this really a feature that people other than the Google protobuf designers want?

If we make an abstraction to fit exactly one use case in the code, it won't make the handling of Google's WKT look any less special-flowery in my opinion.

2020-10-13 04:50 UTC, bkuehnert commented on json.lisp
> +            (value (pi::oneof-value oneof-data)))
The reason that there isn't a general function for doing this is: what happens if the oneof isn't set? What kind of field descriptor do we return in this case?

This leads me to a second problem: I assume that the `kind` oneof in a `Value` is always set here. Per the documentation, it's an error if this isn't the case. I've added an assertion that this is the case, although i'm not really sure if it's the JSON printer's job to validate well-known-type protos. let me know what you think

2020-10-13 04:51 UTC, bkuehnert commented
I have no idea what happened with the commits on this PR. Something about switching emails has borked everything.

Any advice on how to fix it with rebase is greatly appreciated

2020-10-17 01:47 UTC, Slids commented on json.lisp
> +            (value (pi::oneof-value oneof-data)))
I don't know if it's a idea to return the type, c++ doesn't do it, python doens't do it.
Your suggesting modification of a user end function purely for convenience in one place
of our code...

As for the assert, it's fine, or not having it is probably fine, I personally wouldn't think to much.

2020-12-03 20:26 UTC, bkuehnert commented
Closing since #262 implemented these changes

2020-12-03 20:26 UTC, closed without merging